spring:
  datasource:
    url: jdbc:mysql://mysql.sqlpub.com:3306/cscscs?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: cscscs
    password: ae7e891efb97280e
  sql:
    init:
      schema-locations: classpath:db/schema.sql
#      data-locations: classpath:db/data.sql
      mode: always
