server:
  port: 9000
  servlet:
    context-path: /ruiji
logging:
  level:
    com.zcs.ruijiwaimai: debug
spring:
  datasource:
    url: jdbc:mysql://mysql.sqlpub.com:3306/cscscs?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: cscscs
    password: ae7e891efb97280e
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      mode: always
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true    #默认开启驼峰映射
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    banner: false
    db-config:
      id-type: auto
#      table-prefix: tb_